import { CCTVChannel, SafetyAlert, HazardReport, IoTTelemetryPoint, EECIndustrialEstate, SafetyCourse } from './types';

export const INITIAL_CCTV_CHANNELS: CCTVChannel[] = [
  {
    id: 'cam-01',
    name: 'CAM-01: Petrochemical Cracker Unit',
    location: 'Zone A - Section 12',
    zone: 'Zone A',
    status: 'active',
    fps: 30,
    resolution: '1080p (60fps)',
    peopleCount: 4,
    complianceRate: 98.5,
    currentViolations: [],
    feedType: 'petrochemical',
    lastIncidentTime: '2 hrs ago',
  },
  {
    id: 'cam-02',
    name: 'CAM-02: Heavy Metal Stamping Line',
    location: 'Zone B - Stamping Press 04',
    zone: 'Zone B',
    status: 'warning',
    fps: 29,
    resolution: '1080p (30fps)',
    peopleCount: 6,
    complianceRate: 85.0,
    currentViolations: ['Missing Safety Glasses', 'Proximity Danger Zone'],
    feedType: 'stamping',
    lastIncidentTime: '12 mins ago',
  },
  {
    id: 'cam-03',
    name: 'CAM-03: Robotic Welding Enclosure',
    location: 'Zone C - Assembly Cell 02',
    zone: 'Zone C',
    status: 'active',
    fps: 30,
    resolution: '4K UltraHD',
    peopleCount: 3,
    complianceRate: 95.2,
    currentViolations: [],
    feedType: 'welding',
    lastIncidentTime: 'Yesterday',
  },
  {
    id: 'cam-04',
    name: 'CAM-04: High-Bay Logistics & Forklift Bay',
    location: 'Zone D - Loading Dock 08',
    zone: 'Zone D',
    status: 'active',
    fps: 28,
    resolution: '1080p (30fps)',
    peopleCount: 8,
    complianceRate: 92.0,
    currentViolations: ['High-Vis Vest Unbuttoned'],
    feedType: 'logistics',
    lastIncidentTime: '3 days ago',
  },
];

export const INITIAL_SAFETY_ALERTS: SafetyAlert[] = [
  {
    id: 'alt-101',
    timestamp: 'Just now',
    title: 'Missing Hard Hat in Heavy Stamping Zone',
    zone: 'Zone B',
    location: 'Stamping Press 04',
    riskLevel: 'high',
    type: 'ppe_violation',
    details: {
      th: 'ตรวจพบคนงานไม่สวมหมวกนิรภัยใกล้รัศมีแขนกลปั๊มขึ้นรูปโลหะ โซน B',
      en: 'Worker detected without hard hat near metal stamping robotic press radius in Zone B',
      my: 'ဇုန် B ရှိ သတ္တုပုံသွင်းစက်ရုပ်အနီး ဦးထုပ်မပါသော အလုပ်သမားအား တွေ့ရှိရပါသည်',
      km: 'បានរកឃើញកម្មករមិនពាក់មួកសុវត្ថិភាពក្បែរម៉ាស៊ីនកាត់ដែកក្នុងតំបន់ B',
      lo: 'ກວດພົບຄົນງານບໍ່ໃສ່ໝວກນິລະໄພໃກ້ລັດສະໝີເຄື່ອງຈັກປ້ຳໂລຫະ ໂຊນ B',
    },
    audioText: {
      th: 'เตือนอันตราย! กรุณาสวมหมวกนิรภัยทันทีก่อนเข้าพื้นที่ปั๊มโลหะ โซน B',
      en: 'Safety Warning! Please wear your hard hat immediately before entering Zone B',
      my: 'သတိပေးချက်! ဇုန် B အတွင်းသို့ မဝင်မီ ဘေးကင်းရေးဦးထုပ်ကို ချက်ချင်း ဝတ်ဆင်ပါ',
      km: 'ការព្រមាន! សូមពាក់មួកសុវត្ថិភាពជាបន្ទាន់មុនពេលចូលតំបន់ B',
      lo: 'ເຕືອນອັນຕະລາຍ! ກະລຸນາໃສ່ໝວກນິລະໄພທັນທີກ່ອນເຂົ້າເຂດ ໂຊນ B',
    },
    acknowledged: false,
    assignedOfficer: 'Master Somchai P.',
    channelId: 'cam-02',
  },
  {
    id: 'alt-102',
    timestamp: '14 mins ago',
    title: 'Forklift Pedestrian Proximity Alert',
    zone: 'Zone D',
    location: 'Loading Bay 03',
    riskLevel: 'medium',
    type: 'forklift_proximity',
    details: {
      th: 'ระยะห่างระหว่างคนงานเดินเท้าและรถโฟล์กลิฟต์ต่ำกว่า 2 เมตรในช่องทางโหลดสินค้า',
      en: 'Pedestrian worker and forklift proximity is under 2 meters in loading bay',
      my: 'ကုန်တင်လမ်းကြောင်းတွင် ဖော့ကားနှင့် အလုပ်သမား အကွာအဝေး ၂ မီတာအောက် နီးကပ်နေပါသည်',
      km: 'ចម្ងាយរវាងកម្មករដើរ និងឡានលើកទំនិញជិតជាង ២ ម៉ែត្រក្នុងផ្លូវផ្ទុកទំនិញ',
      lo: 'ໄລຍະຫ່າງລະຫວ່າງຄົນງານ ແລະ ລົດຍົກຕ່ຳກວ່າ 2 ແມັດໃນຊ່ອງທາງຂົນຖ່າຍສິນຄ້າ',
    },
    audioText: {
      th: 'ระวังรถโฟล์กลิฟต์! รักษาระยะห่างเพื่อความปลอดภัย',
      en: 'Caution! Forklift operating nearby. Maintain safe clearance',
      my: 'ဖော့ကားကို သတိထားပါ! ဘေးကင်းသောအကွာအဝေးတွင် နေပါ',
      km: 'ប្រយ័ត្នឡានលើកទំនិញ! សូមរក្សាគម្លាតសុវត្ថិភាព',
      lo: 'ລະວັງລົດຍົກ! ຮັກສາໄລຍະຫ່າງເພື່ອຄວາມປອດໄພ',
    },
    acknowledged: true,
    assignedOfficer: 'Master Somchai P.',
    channelId: 'cam-04',
  },
  {
    id: 'alt-103',
    timestamp: '1 hour ago',
    title: 'Toxic Gas H2S Threshold Spike (18.4 ppm)',
    zone: 'Zone A',
    location: 'Catalytic Column #2',
    riskLevel: 'critical',
    type: 'gas_leak',
    details: {
      th: 'เซนเซอร์ตรวจพบก๊าซ H2S ขึ้นสูงเกินค่าเฝ้าระวัง 18.4 ppm ระบบระบายอากาศฉุกเฉินทำงาน',
      en: 'H2S gas sensor detected spike at 18.4 ppm exceeding safety threshold. Emergency ventilation active',
      my: 'H2S အဆိပ်ဓာတ်ငွေ့ ၁၈.၄ ppm သို့ မြင့်တက်လာကြောင်း စစ်ဆေးတွေ့ရှိရပါသည်',
      km: 'ឧបករណ៍ចាប់សញ្ញារកឃើញឧស្ម័ន H2S កើនឡើងដល់ 18.4 ppm លើសកម្រិតសុវត្ថិភាព',
      lo: 'ເຊັນເຊີກວດພົບອາຍພິດ H2S ຂຶ້ນສູງ 18.4 ppm ເກີນຄ່າເຝົ້າລະວັງ',
    },
    audioText: {
      th: 'คำเตือนก๊าซรั่วไหล! บุคลากรในโซน A โปรดปฏิบัติตามขั้นตอนความปลอดภัย',
      en: 'Gas leak warning! Personnel in Zone A execute safety protocol',
      my: 'ဓာတ်ငွေ့ယိုစိမ့်မှု သတိပေးချက်! ဇုန် A မှ လူများ ဘေးကင်းရေး လုပ်ထုံးလုပ်နည်းကို လိုက်နာပါ',
      km: 'ការព្រមានឧស្ម័នលេចធ្លាយ! បុគ្គលិកក្នុងតំបន់ A សូមអនុវត្តតាមនីតិវិធីសុវត្ថិភាព',
      lo: 'ຄຳເຕືອນອາຍພິດຮົ່ວໄຫຼ! ບຸກຄະລາກອນໃນໂຊນ A ປະຕິບັດຕາມມາດຕະການຄວາມປອດໄພ',
    },
    acknowledged: true,
    assignedOfficer: 'Eng. Kridawat T.',
    channelId: 'cam-01',
  },
];

export const INITIAL_HAZARD_REPORTS: HazardReport[] = [
  {
    id: 'HZ-2026-089',
    timestamp: 'Today, 08:30',
    reporterName: 'Aung Min (အောင်မင်း)',
    reporterNationality: 'Myanmar',
    language: 'my',
    zone: 'Zone B',
    location: 'Stamping Press Bay #4',
    category: 'spill',
    title: 'ဆီယိုစိမ့်မှုကြောင့် ချော်လဲနိုင်သောအန္တရာယ် (Hydraulic Oil Leak)',
    descriptionOriginal: 'စက်အောက်ခြေက ဟိုက်ဒရောလစ်ဆီတွေ ယိုကျနေပြီး ကြမ်းပြင်မှာ ချော်လဲနိုင်ပါတယ်။ သန့်ရှင်းရေး အမြန်လုပ်ပေးဖို့ လိုပါတယ်ခင်ဗျာ။',
    descriptionTranslated: 'พบน้ำมันไฮดรอลิกรั่วซึมจากฐานเครื่องจักรเจิ่งนองบนพื้นทางเดิน เสี่ยงต่อการลื่นล้มรุนแรง ขอให้ฝ่ายอาคารส่งทีมทำความสะอาดด่วน',
    severity: 'medium',
    status: 'investigating',
    upvotes: 8,
  },
  {
    id: 'HZ-2026-088',
    timestamp: 'Yesterday, 16:45',
    reporterName: 'Sok Dara (សុខ ដារ៉ា)',
    reporterNationality: 'Cambodian',
    language: 'km',
    zone: 'Zone C',
    location: 'Assembly Conveyor #2',
    category: 'machine_guard',
    title: 'គម្របការពារម៉ាស៊ីនរបូត (Loose Conveyor Safety Guard)',
    descriptionOriginal: 'គម្របដែកការពារខ្សែពានម៉ាស៊ីនរលុង ខ្លាចដៃកម្មករចូលទៅជាប់ ពេលម៉ាស៊ីនដំណើរការ។',
    descriptionTranslated: 'การ์ดครอบสายพานลำเลียงหลวม อาจทำให้มือหรือเสื้อผ้าคนงานติดเข้าไปในลูกกลิ้งขณะเครื่องจักรกำลังหมุน',
    severity: 'high',
    status: 'resolved',
    upvotes: 14,
  },
  {
    id: 'HZ-2026-087',
    timestamp: '2 days ago',
    reporterName: 'Khamphanh (ຄຳພັນ)',
    reporterNationality: 'Laotian',
    language: 'lo',
    zone: 'Zone D',
    location: 'Emergency Exit Stairwell #1',
    category: 'blocked_exit',
    title: 'ກ່ອງສິນຄ້າວາງກີດຂວາງປະຕູໜີໄຟ (Blocked Fire Exit)',
    descriptionOriginal: 'ມີພາເລດໄມ້ ແລະ ກ່ອງລັງສິນຄ້າວາງກອງປິດປະຕູທາງໜີໄຟ ຖ້າມີເຫດສຸກເສີນຈະແລ່ນອອກບໍ່ໄດ້.',
    descriptionTranslated: 'มีพาเลทไม้และกล่องสินค้าซ้อนทับกันขวางหน้าประตูหนีไฟฉุกเฉิน หากเกิดเพลิงไหม้จะไม่สามารถผลักประตูออกได้',
    severity: 'high',
    status: 'resolved',
    upvotes: 19,
  },
];

export const INITIAL_IOT_TELEMETRY: IoTTelemetryPoint[] = [
  {
    id: 'iot-za',
    zone: 'Zone A',
    name: 'Zone A: Petrochemical Column Unit',
    toxicGasH2S: 4.8,
    toxicGasCO: 12.2,
    temperature: 34.5,
    humidity: 62.0,
    noiseLevel: 78.4,
    vibration: 2.1,
    powerConsumption: 142.8,
    interlockActive: false,
    status: 'normal',
    lastUpdated: '1s ago',
  },
  {
    id: 'iot-zb',
    zone: 'Zone B',
    name: 'Zone B: Metal Stamping & Hydraulic Bay',
    toxicGasH2S: 1.2,
    toxicGasCO: 18.6,
    temperature: 38.2,
    humidity: 58.4,
    noiseLevel: 89.2,
    vibration: 5.8,
    powerConsumption: 280.5,
    interlockActive: false,
    status: 'warning',
    lastUpdated: '1s ago',
  },
  {
    id: 'iot-zc',
    zone: 'Zone C',
    name: 'Zone C: Robotic Welding & Laser Line',
    toxicGasH2S: 0.5,
    toxicGasCO: 8.4,
    temperature: 31.8,
    humidity: 50.1,
    noiseLevel: 82.0,
    vibration: 1.8,
    powerConsumption: 95.4,
    interlockActive: false,
    status: 'normal',
    lastUpdated: '1s ago',
  },
  {
    id: 'iot-zd',
    zone: 'Zone D',
    name: 'Zone D: Warehouse Loading & Battery Station',
    toxicGasH2S: 0.2,
    toxicGasCO: 14.1,
    temperature: 32.0,
    humidity: 55.0,
    noiseLevel: 74.5,
    vibration: 0.9,
    powerConsumption: 64.0,
    interlockActive: false,
    status: 'normal',
    lastUpdated: '1s ago',
  },
];

export const EEC_INDUSTRIAL_ESTATES: EECIndustrialEstate[] = [
  {
    id: 'eec-map-ta-phut',
    name: 'Map Ta Phut Industrial Estate (มาบตาพุด)',
    province: 'Rayong',
    totalFactories: 142,
    monitoredFactories: 118,
    totalWorkers: 28400,
    migrantWorkerRatio: 0.46,
    safetyScore: 96.4,
    incidentRatePerThousand: 3.1,
    activeAlerts: 1,
    riskStatus: 'low',
    coordinates: { x: 55, y: 72 },
  },
  {
    id: 'eec-amata-chonburi',
    name: 'Amata City Chonburi (อมตะซิตี้ ชลบุรี)',
    province: 'Chonburi',
    totalFactories: 720,
    monitoredFactories: 540,
    totalWorkers: 112000,
    migrantWorkerRatio: 0.52,
    safetyScore: 94.2,
    incidentRatePerThousand: 4.2,
    activeAlerts: 3,
    riskStatus: 'medium',
    coordinates: { x: 38, y: 32 },
  },
  {
    id: 'eec-amata-rayong',
    name: 'Amata City Rayong (อมตะซิตี้ ระยอง)',
    province: 'Rayong',
    totalFactories: 310,
    monitoredFactories: 265,
    totalWorkers: 58000,
    migrantWorkerRatio: 0.54,
    safetyScore: 93.8,
    incidentRatePerThousand: 4.5,
    activeAlerts: 2,
    riskStatus: 'medium',
    coordinates: { x: 68, y: 58 },
  },
  {
    id: 'eec-laem-chabang',
    name: 'Laem Chabang Port & Estate (แหลมฉบัง)',
    province: 'Chonburi',
    totalFactories: 220,
    monitoredFactories: 198,
    totalWorkers: 45000,
    migrantWorkerRatio: 0.49,
    safetyScore: 95.0,
    incidentRatePerThousand: 3.8,
    activeAlerts: 1,
    riskStatus: 'low',
    coordinates: { x: 42, y: 52 },
  },
  {
    id: 'eec-wha-eastern',
    name: 'WHA Eastern Seaboard (ดับบลิวเอชเอ อีสเทิร์นซีบอร์ด)',
    province: 'Rayong',
    totalFactories: 280,
    monitoredFactories: 240,
    totalWorkers: 52000,
    migrantWorkerRatio: 0.51,
    safetyScore: 94.8,
    incidentRatePerThousand: 3.9,
    activeAlerts: 2,
    riskStatus: 'low',
    coordinates: { x: 62, y: 48 },
  },
  {
    id: 'eec-gateway-city',
    name: 'Gateway City Industrial Estate (เกตเวย์ ซิตี้)',
    province: 'Chachoengsao',
    totalFactories: 110,
    monitoredFactories: 88,
    totalWorkers: 22000,
    migrantWorkerRatio: 0.48,
    safetyScore: 93.2,
    incidentRatePerThousand: 4.8,
    activeAlerts: 2,
    riskStatus: 'medium',
    coordinates: { x: 50, y: 18 },
  },
];

export const SAFETY_COURSES: SafetyCourse[] = [
  {
    id: 'course-ppe-01',
    category: 'basic_ppe',
    title: {
      th: 'อุปกรณ์คุ้มครองความปลอดภัยส่วนบุคคล 5 ประการ',
      en: '5 Core Personal Protective Equipment (PPE) Essentials',
      my: 'မရှိမဖြစ် တစ်ကိုယ်ရေ အကာအကွယ်ပစ္စည်း ၅ မျိုး',
      km: 'ឧបករណ៍ការពារសុវត្ថិភាពផ្ទាល់ខ្លួន ៥ យ៉ាង',
      lo: 'ອຸປະກອນປ້ອງກັນຄວາມປອດໄພສ່ວນບຸກຄົນ 5 ຢ່າງ',
    },
    durationMin: 5,
    xpPoints: 100,
    icon: 'ShieldCheck',
    completed: true,
    score: 100,
    summary: {
      th: 'เรียนรู้วิธีการสวมใส่ ตรวจสอบ และดูแลรักษา หมวก เสื้อสะท้อนแสง แว่นตา ถุงมือ และรองเท้านิรภัยอย่างถูกต้อง',
      en: 'Learn how to wear, inspect, and maintain helmets, hi-vis vests, goggles, gloves, and safety shoes properly.',
      my: 'ဦးထုပ်၊ ရောင်ပြန်အင်္ကျီ၊ မျက်မှန်၊ လက်အိတ်နှင့် ဖိနပ်များကို မှန်ကန်စွာ ဝတ်ဆင်ထိန်းသိမ်းနည်း',
      km: 'រៀនពីរបៀបពាក់ ពិនិត្យ និងថែទាំមួក អាវ វ៉ែនតា ស្រោមដៃ និងស្បែកជើងសុវត្ថិភាពឱ្យបានត្រឹមត្រូវ',
      lo: 'ຮຽນຮູ້ວິທີການໃສ່ ກວດສອບ ແລະ ຮັກສາໝວກ ເສື້ອ ແວ່ນຕາ ຖົງມື ແລະ ເກີບນິລະໄພຢ່າງຖືກຕ້ອງ',
    },
    keyRules: {
      th: [
        '1. ต้องสวมหมวกนิรภัยและรัดสายคางทุกครั้งก่อนเข้าพื้นที่ทำงาน',
        '2. เสื้อสะท้อนแสงต้องติดกระดุม/ซิปให้เรียบร้อยเพื่อการมองเห็นในระยะไกล',
        '3. รองเท้าหัวเหล็กต้องผูกเชือกให้แน่นเพื่อป้องกันของหนักตกทับ',
      ],
      en: [
        '1. Always fasten chin straps when wearing a hard hat.',
        '2. Keep hi-vis vest zipped for 360-degree visibility.',
        '3. Ensure steel-toe laces are secure against heavy impacts.',
      ],
      my: [
        '၁။ ဦးထုပ်ဆောင်းတိုင်း မေးသိုင်းကြိုးကို သေချာစွာ တပ်ဆင်ပါ။',
        '၂။ အဝေးမှမြင်နိုင်ရန် ရောင်ပြန်အင်္ကျီ ဇစ်ကို သေချာပိတ်ပါ။',
        '၃။ အလေးအပင်ပြုတ်ကျဒဏ်မှ ကာကွယ်ရန် ဖိနပ်ကြိုးကို တင်းကျပ်စွာ စည်းပါ။',
      ],
      km: [
        '១. ត្រូវពាក់មួកសុវត្ថិភាព និងចងខ្សែចង្កាឱ្យជាប់រាល់ពេលចូលកន្លែងធ្វើការ',
        '២. អាវឆ្លុះពន្លឺត្រូវទាញរ៉ូតឱ្យជិត ដើម្បីឱ្យគេមើលឃើញពីចម្ងាយ',
        '៣. ស្បែកជើងសុវត្ថិភាពត្រូវចងខ្សែឱ្យតឹង ដើម្បីការពាររបស់ធ្ងន់ធ្លាក់សង្កត់',
      ],
      lo: [
        '1. ຕ້ອງໃສ່ໝວກນິລະໄພ ແລະ ຮັດສາຍຄາງທຸກຄັ້ງກ່ອນເຂົ້າພື້ນທີ່ເຮັດວຽກ',
        '2. ເສື້ອສະທ້ອນແສງຕ້ອງຮູດຊິບໃຫ້ຮຽບຮ້ອຍເພື່ອການເບິ່ງເຫັນໃນໄລຍະໄກ',
        '3. ເກີບຫົວເຫຼັກຕ້ອງມັດສາຍໃຫ້ແໜ້ນເພື່ອປ້ອງກັນສິ່ງຂອງໜັກຕົກທັບ',
      ],
    },
    quiz: [
      {
        question: {
          th: 'เมื่อต้องทำงานใกล้เครื่องจักรหมุนความเร็วสูง ข้อใดถูกต้อง?',
          en: 'When working near high-speed rotating machinery, which rule is correct?',
          my: 'အမြန်နှုန်းမြင့် လည်ပတ်နေသော စက်အနီး အလုပ်လုပ်ရာတွင် မည်သည့်အချက် မှန်ကန်သနည်း။',
          km: 'នៅពេលធ្វើការក្បែរម៉ាស៊ីនវិលល្បឿនលឿន តើចំណុចណាត្រឹមត្រូវ?',
          lo: 'ເມື່ອຕ້ອງເຮັດວຽກໃກ້ເຄື່ອງຈັກໝູນຄວາມໄວສູງ ຂໍ້ໃດຖືກຕ້ອງ?',
        },
        options: {
          th: [
            'สวมเสื้อผ้าหลวมๆ เพื่อระบายความร้อน',
            'สวมเสื้อรัดกุม เก็บชายเสื้อ ห้ามใส่เครื่องประดับหรือถุงมือหลวม',
            'ใส่ผ้าพันคอเพื่อกันฝุ่น',
            'ถอดหมวกนิรภัยเพื่อความคล่องตัว',
          ],
          en: [
            'Wear loose clothes for ventilation',
            'Wear snug clothing, tuck in shirts, no loose gloves or jewelry',
            'Wear a long scarf to block dust',
            'Remove helmet for agility',
          ],
          my: [
            'အပူသက်သာစေရန် အဝတ်ချောင်ချောင် ဝတ်ဆင်ပါ',
            'အင်္ကျီကို သပ်ရပ်စွာ ဝတ်ဆင်ပြီး လက်ဝတ်ရတနာနှင့် လက်အိတ်ချောင်များ မဝတ်ရ',
            'ဖုန်မှုန့်ကာကွယ်ရန် လည်စည်း ရှည်ရှည် ပတ်ပါ',
            'ပေါ့ပါးစေရန် ဦးထုပ် ချွတ်ထားပါ',
          ],
          km: [
            'ពាក់សម្លៀកបំពាក់រលុងៗដើម្បីឱ្យត្រជាក់',
            'ពាក់សម្លៀកបំពាក់រៀបរយ ញាត់ជាយអាវចូលក្នុង ហាមពាក់គ្រឿងអលង្ការ ឬស្រោមដៃរលុង',
            'ពាក់កន្សែងវែងដើម្បីបាំងធូលី',
            'ដោះមួកសុវត្ថិភាពចេញដើម្បីស្រួលធ្វើការ',
          ],
          lo: [
            'ໃສ່ເສື້ອຜ້າຫຼວມໆເພື່ອລະບາຍຄວາມຮ້ອນ',
            'ໃສ່ເສື້ອຜ້າຮັດກຸມ ເກັບຊາຍເສື້ອ ຫ້າມໃສ່ເຄື່ອງປະດັບຫຼືຖົງມືຫຼວມ',
            'ໃສ່ຜ້າພັນຄໍເພື່ອປ້ອງກັນຝຸ່ນ',
            'ຖອດໝວກນິລະໄພເພື່ອຄວາມຄ່ອງຕົວ',
          ],
        },
        correctIndex: 1,
        explanation: {
          th: 'เสื้อผ้าหลวม ชายเสื้อ หรือถุงมือหลวม อาจถูกเพลาหรือลูกกลิ้งเครื่องจักรดูดเข้าไปจนเกิดอุบัติเหตุร้ายแรง',
          en: 'Loose garments or oversized gloves can be snagged by rotating shafts causing severe crushing injuries.',
          my: 'အဝတ်အစားချောင်များ သို့မဟုတ် လက်အိတ်များသည် လည်ပတ်နေသော စက်ရဟတ်အတွင်းသို့ ညပ်ပါသွားနိုင်ပါသည်။',
          km: 'សម្លៀកបំពាក់រលុង ឬស្រោមដៃធំពេក អាចនឹងត្រូវម៉ាស៊ីនវិលទាញចូលបណ្តាលឱ្យមានគ្រោះថ្នាក់ធ្ងន់ធ្ងរ',
          lo: 'ເສື້ອຜ້າຫຼວມ ຫຼື ຖົງມືຫຼວມ ອາດຖືກເພົາເຄື່ອງຈັກດູດເຂົ້າໄປຈົນເກີດອຸບັດຕິເຫດຮ້າຍແຮງ',
        },
      },
    ],
  },
  {
    id: 'course-chem-02',
    category: 'chemical',
    title: {
      th: 'ความปลอดภัยในการจัดการสารเคมีและวัตถุไวไฟ (GHS)',
      en: 'Chemical Safety & GHS Hazard Communication',
      my: 'ဓာတုပစ္စည်းနှင့် မီးလောင်လွယ်သော ပစ္စည်းများ ဘေးကင်းရေး (GHS)',
      km: 'សុវត្ថិភាពក្នុងការគ្រប់គ្រងសារធាតុគីមី និងវត្ថុងាយឆេះ (GHS)',
      lo: 'ຄວາມປອດໄພໃນການຈັດການສານເຄມີ ແລະ ວັດຖຸໄວໄຟ (GHS)',
    },
    durationMin: 8,
    xpPoints: 150,
    icon: 'FlaskConical',
    completed: false,
    summary: {
      th: 'เข้าใจสัญลักษณ์เตือนสารเคมี GHS การใช้อุปกรณ์ช่วยหายใจ หน้ากากกรองสารพิษ และการปฐมพยาบาลเมื่อสารเคมีกระเด็น',
      en: 'Understand GHS chemical hazard pictograms, proper respirator usage, and eye wash decontamination steps.',
      my: 'GHS ဓာတုဗေဒ သင်္ကေတများ၊ အသက်ရှူမျက်နှာဖုံး အသုံးပြုနည်းနှင့် အရေးပေါ် ရှေးဦးသူနာပြုနည်းများ',
      km: 'ស្វែងយល់ពីសញ្ញាព្រមាន GHS ការប្រើប្រាស់ម៉ាស់ការពារឧស្ម័នពុល និងការសង្គ្រោះបឋម',
      lo: 'ເຂົ້າໃຈສັນຍາລັກເຕືອນສານເຄມີ GHS ການໃຊ້ໜ້າກາກກອງອາຍພິດ ແລະ ການປະຖົມພະຍາບານເບື້ອງຕົ້ນ',
    },
    keyRules: {
      th: [
        '1. ตรวจสอบป้าย SDS ก่อนสัมผัสหรือเคลื่อนย้ายถังเคมีทุกครั้ง',
        '2. สวมแว่นครอบตากันสารเคมี (Chemical Goggles) และถุงมือยางไนไตรล์',
        '3. หากสารเคมีเข้าตา ล้างน้ำสะอาดที่สถานีฉุกเฉินต่อเนื่องอย่างน้อย 15 นาที',
      ],
      en: [
        '1. Inspect Safety Data Sheet (SDS) before handling chemical containers.',
        '2. Always wear splash-proof chemical goggles and nitrile gloves.',
        '3. In case of eye contact, flush with clean water at eyewash station for 15 minutes.',
      ],
      my: [
        '၁။ ဓာတုပစ္စည်းများ မကိုင်တွယ်မီ SDS အချက်အလက်ကို အမြဲစစ်ဆေးပါ။',
        '၂။ ဓာတုကာကွယ်ရေး မျက်မှန်နှင့် လက်အိတ်ကို အမြဲဝတ်ဆင်ပါ။',
        '၃။ ဓာတုပစ္စည်း မျက်စိထဲဝင်ပါက မျက်လုံးဆေးစခန်းတွင် အနည်းဆုံး ၁၅ မိနစ် ရေဆေးပါ။',
      ],
      km: [
        '១. ពិនិត្យស្លាក SDS រាល់ពេលមុនពេលប៉ះពាល់ ឬផ្លាស់ទីធុងគីមី',
        '២. ពាក់វ៉ែនតាការពារជាតិគីមី និងស្រោមដៃកៅស៊ូជានិច្ច',
        '៣. ប្រសិនបើសារធាតុគីមីចូលភ្នែក ត្រូវលាងទឹកស្អាតនៅកន្លែងលាងភ្នែកបន្ទាន់យ៉ាងតិច ១៥ នាទី',
      ],
      lo: [
        '1. ກວດສອບປ້າຍ SDS ກ່ອນສຳຜັດຫຼືເຄື່ອນຍ້າຍຖັງເຄມີທຸກຄັ້ງ',
        '2. ໃສ່ແວ່ນຕາກັນສານເຄມີ ແລະ ຖົງມືຢາງໄນໄຕຣລ໌ທຸກຄັ້ງ',
        '3. ຫາກສານເຄມີເຂົ້າຕາ ລ້າງນ້ຳສະອາດຕໍ່ເນື່ອງຢ່າງໜ້ອຍ 15 ນາທີ',
      ],
    },
    quiz: [
      {
        question: {
          th: 'สัญลักษณ์รูปเปลวไฟบนวงกลม (Flame over circle) หมายถึงอะไร?',
          en: 'What does the GHS "Flame over circle" pictogram signify?',
          my: 'စက်ဝိုင်းပေါ်ရှိ မီးတောက်သင်္ကေတ (Flame over circle) သည် အဘယ်အရာကို ဆိုလိုသနည်း။',
          km: 'សញ្ញាអណ្តាតភ្លើងលើរង្វង់ (Flame over circle) មានន័យដូចម្តេច?',
          lo: 'ສັນຍາລັກຮູບແປວໄຟເທິງວົງມົນ ໝາຍເຖິງຫຍັງ?',
        },
        options: {
          th: [
            'สารกัดกร่อนผิวหนัง',
            'สารออกซิไดซ์ (เพิ่มความรุนแรงของไฟ)',
            'ก๊าซภายใต้ความดัน',
            'สารพิษเฉียบพลัน',
          ],
          en: [
            'Corrosive substance',
            'Oxidizing agent (intensifies fire)',
            'Gases under pressure',
            'Acute toxic substance',
          ],
          my: [
            'အသားအရေကို လောင်ကျွမ်းစေသော ပစ္စည်း',
            'အောက်ဆီဂျင်ထုတ်ပေးပြီး မီးကို ပိုမိုပြင်းထန်စေသော ပစ္စည်း (Oxidizer)',
            'ဖိအားမြင့် ဓာတ်ငွေ့',
            'ပြင်းထန်သော အဆိပ်',
          ],
          km: [
            'សារធាតុកាត់ស្បែក',
            'សារធាតុអុកស៊ីតកម្ម (បង្កើនកម្តៅ និងការឆេះ)',
            'ឧស្ម័នក្រោមសម្ពាធ',
            'សារធាតុពុលធ្ងន់ធ្ងរ',
          ],
          lo: [
            'ສານກັດກ່ອນຜິວໜັງ',
            'ສານອົກຊີໄດຊ໌ (ເພີ່ມຄວາມຮຸນແຮງຂອງໄຟ)',
            'ອາຍແກັສພາຍໃຕ້ຄວາມດັນ',
            'ສານພິດຮ້າຍແຮງ',
          ],
        },
        correctIndex: 1,
        explanation: {
          th: 'สารออกซิไดซ์สามารถให้ออกซิเจนและเร่งให้วัตถุอื่นติดไฟอย่างรุนแรง ต้องเก็บแยกจากสารไวไฟเด็ดขาด',
          en: 'Oxidizers provide oxygen that can cause flammable materials to burn violently and must be stored separately.',
          my: 'အောက်ဆီဂျင်ထုတ်ပေးသော ပစ္စည်းများသည် အခြားပစ္စည်းများကို မီးလောင်လွယ်စေသဖြင့် သီးသန့်ခွဲထားရမည်။',
          km: 'សារធាតុអុកស៊ីតកម្មអាចបញ្ចេញអុកស៊ីសែន និងធ្វើឱ្យវត្ថុផ្សេងទៀតឆេះយ៉ាងសន្ធោសន្ធៅ',
          lo: 'ສານອົກຊີໄດຊ໌ສາມາດເລັ່ງໃຫ້ວັດຖຸອື່ນຕິດໄຟຢ່າງຮຸນແຮງ ຕ້ອງເກັບແຍກຕ່າງຫາກ',
        },
      },
    ],
  },
];

export const HISTORICAL_ACCIDENT_DATA = [
  { month: 'Jan 2568', before: 24, after: 15, alerts: 120, responseMin: 18.5 },
  { month: 'Feb 2568', before: 22, after: 13, alerts: 135, responseMin: 15.2 },
  { month: 'Mar 2568', before: 26, after: 12, alerts: 142, responseMin: 12.0 },
  { month: 'Apr 2568', before: 21, after: 10, alerts: 150, responseMin: 9.4 },
  { month: 'May 2568', before: 25, after: 8, alerts: 148, responseMin: 7.2 },
  { month: 'Jun 2568', before: 23, after: 6, alerts: 155, responseMin: 6.8 },
];

export const PILOT_TRIAL_STATS = {
  modelAccuracy: 94.2,
  precision: 93.1,
  recall: 95.3,
  f1Score: 94.2,
  verifiedAlerts: 142,
  responseTimeReduction: -62, // -62%
  accidentReduction: -37, // -37%
  pilotFactories: 2,
};
